import 'package:share_sampatti_mvp/app/app.dart';

class TermsAndConditionsScreen extends ConsumerWidget {
  const TermsAndConditionsScreen({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final appDimensions = ref.watch(appDimensionsProvider);

    return Scaffold(
      appBar: CustomAppBar.appbar(context, "Terms and Conditions"),
      body: SingleChildScrollView(
        padding: EdgeInsets.all(appDimensions.horizontalPaddingM),
        child: Column(
          children: [
            Inter(
              text:
                  "These terms of use (“Terms”) mandate the terms on which the user ( “You” or Your” or “Yourself” or “User”) access and register on the website www.ShareSampatti. com and its mobile application operated by Share Sampatti Private Limited (“Company”),collectively referred tp as (“Platform”). The Company through the platform enables individualand institutional investors to invest in and earn long terms gains, periodic short-term revenue and certain community benefits from curated real estate assets (“Property” or “Properties”).",
              letterSpacing: 1,
              fontWeight: FontWeight.w500,
            ),
            SizedBox(height: appDimensions.verticalSpaceL),

            Inter(
              text:
                  "These Terms are an electronic record in terms of the Information Technology Act, 2000 and rules made thereunder (as applicable) that are generated by a computer system and do not require any physical, electronic, or digital signatures.",
              letterSpacing: 1,
              fontWeight: FontWeight.w500,
            ),
            SizedBox(height: appDimensions.verticalSpaceL),

            Inter(
              text:
                  "Please read these Terms of Use (“Terms”) and the please policy carefully before using or registering on the Platform or accessing any material, information, etc., through the Platform. By clicking on the ‘I Accept’ button provided at the sign up page, You accept these Terms and the Privacy Policy and agree to be legally bound by the same and You shall not claim invalidity of these Terms merely on the grounds that it is being concluded electronically.",
              letterSpacing: 1,
              fontWeight: FontWeight.w500,
            ),
            SizedBox(height: appDimensions.verticalSpaceL),

            Inter(
              text:
                  "For the aforesaid purposes, Your affirmative action in clicking on ‘check box’ and on the ‘I Accept’ button while registering or transacting as a User (including availing any Services (as defined below on the Platform) implies Your acceptance.",
              letterSpacing: 1,
              fontWeight: FontWeight.w500,
            ),
          ],
        ),
      ),
    );
  }
}
