name: Build and Release Flutter App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0' # use your Flutter SDK version

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload build artifact (APK)
        uses: actions/upload-artifact@v4
        with:
          name: flutter-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      # If you also want an iOS build (only works on macOS runners)
      # - name: Build iOS
      #   if: runner.os == 'macOS'
      #   run: flutter build ios --release

      # - name: Upload iOS artifact
      #   if: runner.os == 'macOS'
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: flutter-ios
      #     path: build/ios/ipa
